name: MMOProDrop
version: ${project.version}
main: com.yourname.mmoprodro.MMOProDrop
# Cập nhật api-version lên 1.21
api-version: '1.21'
depend: [MMOItems]
author: YourName
description: Giải pháp drop chuyên nghiệp, chống farm và hỗ trợ điều kiện cho MMOItems.
commands:
  mmoprodro:
    description: Lệnh chính của MMOProDrop.
    usage: /<command> [reload]
    aliases: [mpro, mmopro]
    permission: mmoprodro.admin